# Exceptions
1. Napisz funkcjê o nag³ówku double dziel(double a, double b), której wynikiem bêdzie iloraza/b. Jeœli argument b bêdzie liczb¹ zero wyrzuæ wyj¹tek typu std::string. Nastêpnie wywo³aj funkcjê w mainie i odpowiednio obs³u¿ wyj¹tek wypisuj¹c rzucony string.
2. Stwórz obiekt klasy std::vector<int> o wielkoœci 5, a nastêpnie spróbuj siê odnieœæ do szóstego elementu tablicy za pomoc¹ operatora indeksowania []. Co siê sta³o po uruchomieniu programu? Nastêpnie do dostania siê do 6 elementu tablicy u¿yj funkcji at(). Przetestuj dzia³anie programu. Nastêpnie otocz wywo³anie funkcji blokiem try, przechwyæ wyj¹tek typu std::out_of_range i obs³u¿ go. Przetestuj dzia³anie programu raz jeszcze.
3. W pliku OpenFile.h istnieje funkcja otwieraj¹ca plik tekstowy. W przypadku kiedy otwarcie pliku nie powiedzie siê jej dzia³anie jest przerywane za pomoc¹ return; Stwórz w³asny wyj¹tek dziedzicz¹cy pod std::runtime_error, przyjmuj¹cy w konstruktorze nazwê pliku i wywo³uj¹ca konstruktor std::runtime_error tak, ¿eby wiadomoœc wypisywana przez funkcjê what brzmia³a "Can't open file: " + nazwaPliku. Nastêpnie wywo³aj funkcjê w mainie i obs³u¿ wyj¹tek. 
4. Stwórz funkcjê w której deklaracji, po jej nazwie zawrzesz s³owo kluczowe noexcept.  Spróbuj wyrzuciæ w tej funkcji jakikolwiek wyj¹tek i wywo³aæ j¹. Co siê sta³o? 
5. Zmieñ obs³uge wyj¹tku z zadania trzeciego tak, ¿eby po bloku try by³y dwa blocki catch - pierwszy przechwytuj¹cy std::runtime_error, drugi stworzony przez ciebie wyj¹tek. Który z bloków przechwyci wyrzucony wyj¹tek? 